name: bff
replicaCount: 1
container:
  image:
    repository: keigokida/gomicroservices
    tag: bff
    pullPolicy: Always
  dns:
    query: payment-service
    command: order-service

service:
  type: NodePort
  port: 8080
  paymentPort: 8081
  orderPort: 8082
