name: inventory-service
replicaCount: 1
container:
  image:
    repository: keigokida/gomicroservices
    tag: payment_service
    pullPolicy: Always
  dns:
    payment: payment-service
    inventory: inventory-service

service:
  type: ClusterIP
  port: 8082
  paymentPort: 8081
  orderPort: 8082
