name: payment-service
replicaCount: 1
container:
  image:
    repository: keigokida/gomicroservices
    tag: order_service
    pullPolicy: Always
  dns:
    payment: payment-service
    order: order-service

service:
  type: ClusterIP
  port: 8081
  paymentPort: 8081
  orderPort: 8082
